import type { Metadata } from "next"
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google"
import "./globals.css"
import { AntConfigProvider } from "@/components/AntConfigProvider"
import { SmoothScroll } from "@/components/SmoothScroll"

const ibm_plex = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
})

const ibm_plex_mono = IBM_Plex_Mono({
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"]
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${ibm_plex.variable} ${ibm_plex_mono.variable} ${ibm_plex.className} antialiased`}
      >
        <AntConfigProvider>
          <SmoothScroll>
            <div className="">

              {children}
            </div>
          </SmoothScroll>
        </AntConfigProvider>
      </body>
    </html>
  )
}
